// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7u862pa3G5ye4Xt9djgQ2uHStjLF95aI',
    appId: '1:558799447150:android:f1383456622474d855327f',
    messagingSenderId: '558799447150',
    projectId: 'crud-fffa3',
    storageBucket: 'crud-fffa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDziWYMt-tih3snj6vMxfkSePv8TYnpPr8',
    appId: '1:558799447150:ios:3fcef22cba7e408455327f',
    messagingSenderId: '558799447150',
    projectId: 'crud-fffa3',
    storageBucket: 'crud-fffa3.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0f6wlKU57rQQSDHTrbSAGfCg06E6213s',
    appId: '1:558799447150:web:2d6e837eaf8b0c1a55327f',
    messagingSenderId: '558799447150',
    projectId: 'crud-fffa3',
    authDomain: 'crud-fffa3.firebaseapp.com',
    storageBucket: 'crud-fffa3.firebasestorage.app',
    measurementId: 'G-PBDY5KP131',
  );

}